development: &default
  adapter: postgresql
  encoding: unicode
  host: localhost

production:
  <<: *default
  database: reimburse_production

development:
  <<: *default
  database: reimburse_development

test:
  <<: *default
  database: reimburse_test
